### ISSUE TITLE
create classes for tables in database

### ISSUE THREAD

**Issue by spasynkov** [spasynkov/utilities-expense#1]
@Rymar4ik create *DataSet classes  in /src/main/java/database/ for tables from database.
for example: for table 'users' create class UsersDataSet in /src/main/java/database/users

we should get someting like this: 
![tables](https://cloud.githubusercontent.com/assets/14253682/13556935/29cfc168-e3ee-11e5-942c-63cd3cb23e56.png)
we will add relations later, so only tables/classes now

**Comment by spasynkov** [comment]
in  /src/main/java/database we should have packages for every table in database. in every package - one class named like tablenameDataSet

and dont forget to create new branch for this :D

**Comment by Rymar4ik** [comment]
ok. trying resolve this

**Comment by Rymar4ik** [comment]
resolve
